Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 4/9/2024
Var
x, r, c : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

repita
leia(c)
r<-x*3
escreval("R:",r)
c<-c+1

ate (c>=5)

Fimalgoritmo